### ISSUE TITLE
Selecting a word and right clicking de-selects the word

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2409]
Description of problem:

Steps to reproduce:
1.open tinymce 4 with content "hello world"
2.double click "world" to select it
3.right click with mouse
4.
5.

Expected result: context menu opens up with the "world" still selected

Actual result: context menu opens up, but the selection goes away and becomes regular cursor

> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T7704](http://archive.tinymce.com/develop/bugtracker_view.php?id=7704) posted by [minhur](http://archive.tinymce.com/profile.php?name=minhur)_

> _**Tags:** [firefox msie safari chrome contextmenu rightclick highlight]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by HaraldWalker** [comment]
Same with images. Select an image, right click, image is being deselected, insert/edit image of context menu is not using the image properties.

**Comment by spocke** [comment]
I think this issue is os dependent. Mac OS and Windows work differently here if I remember correctly.

**Comment by HaraldWalker** [comment]
I've added version numbers and OS to my previous comment. Both the word and image deselect issues are reproducible on https://www.tinymce.com/docs/demo/full-featured/.

**Comment by spocke** [comment]
Need to investigate what the right behavior is here. Since if it's os dependent then users might expect native behavior.

**Comment by HaraldWalker** [comment]
Loosing a selection when selecting a contextual menu item is not OS X native behavior. At the moment this means you can't edit image properties unless you click on the image icon in the toolbar but you can't edit in Chrome/Safari OS X when using the contextual menu.

OS X 10.10 + Chrome 47: Not ok
OS X 10.10 + Safari 9: Not ok
OS X 10.10 + Firefox 42: OK
Windows 8.1 + IE 11: OK
Windows 8.1 + Chrome 47: OK
Windows 8.1 + Firefox 42: OK

**Comment by spocke** [comment]
Yes, but for some odd reason Chrome/Safari on Mac has custom behavior and I'm guessing it's for a reason not sure what though. We had fixed this in the past then we had to remove the fix since it broke other things will try to find that commit.

**Comment by spocke** [comment]
Currently don't have access to a mac will check this next week but in the mean time what happens if you remove this fix.
https://github.com/tinymce/tinymce/blob/master/js/tinymce/plugins/contextmenu/plugin.js#L30

Could be that these lines now cause more harm than good.

**Comment by HaraldWalker** [comment]
Yes, by not calling editor.selection.setRng the problem is solved for image and text selections. What issue did it try to solve? I guess issue 7022 is not in Github.

**Comment by spocke** [comment]
I think it was that the caret wasn't moved at all before. So you couldn't select things with the right mouse button.

**Comment by weshulsizer** [comment]
Was a solution or reason found with this issue?

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.

**Comment by pesla** [comment]
This definitely is still an issue @blackcathikari. I can reproduce this with `4.4.1`.

To reproduce:

1. Open the [demo](https://www.tinymce.com/docs/demo/full-featured/) (I'm using `Version 54.0.2823.0 canary (64-bit)` on `OS X`).
2. Select some text.
3. Right-click.

You'll notice that text selection is removed.

**Comment by spocke** [comment]
The fix for #1760 produces this behavior. But I can no longer reproduce #1760 when I remove that fix so I guess we should probably get rid of that.

**Comment by spocke** [comment]
This is now fixed in this commit: https://github.com/tinymce/tinymce/commit/efc7af28428c804bbc669ba9c1e691c85f33574d

**Comment by webmasterpdx** [comment]
This is a bug in chrome. Did you try it in firefox? If you go to facebook, for example, and find a post with some comments below it, where the person's name is on the left in blue with the comment starting on the same line, select the first few words of the comments. Then right click on it, the selection will disappear, the paragraph will highlight quickly and reformat, and your selection will disappear. I've also seen it in google search results occasionally. The problem doesn't seem to be in firefox.
