### ISSUE TITLE
Web Component support breaks WordPress in Safari Technology Preview

### ISSUE THREAD

**Issue by apple-web-evangelist** [tinymce/tinymce#2894]
Note that the use of `event.deepPath[0]` in `js/tinymce/classes/dom/EventUtils.js` assumes `deepPath` is an attribute instead of a method.

See https://github.com/whatwg/dom/issues/242

This currently breaks wordpress.com sites an open-source WordPress version 4.5+ sites in Safari Technology Preview. WordPress is using TinyMCE 4.3.10.

**Comment by spocke** [comment]
I beleave this was fixed in TinyMCE 4.3.9 but it doesn't seem to be released on wordpress.com also we removed all shadow dom related logic now for the next release so either way this is fixed.

**Comment by apple-web-evangelist** [comment]
As far as I can see the code was originally added in TinyMCE 4.3.4 with PR #2459 (4c9fabcbad653d7c14a40e64bcce44786e960e5c), then a follow-up fix was made (3c6f72e4020550ecd02be34dc082ae0b81ff7b78) which shipped in TinyMCE 4.3.9 and continues to exist through the 4.3.11 tagged code.

The fix that you're referring to didn't fix this issue because it speculatively references the `deepPath` attribute as an array, but in Safari Technology Preview it is implemented as a method as per the current draft: http://w3c.github.io/webcomponents/spec/shadow/#extensions-to-event-interface

That said it does look like a18a1142338eb281416ff86097a1a54783bc0996 addresses this issue completely. I was going to complain about implementing in-progress spec, but it looks like you've put it behind a flag that appears to be default off. Kudos for the fast work.

**Comment by aduth** [comment]
>I believe this was fixed in TinyMCE 4.3.9 but it doesn't seem to be released on wordpress.com

We've just upgraded from 4.3.8 to 4.3.11 on WordPress.com, and issues previously observed under 4.3.8 in Safari Tech Preview (notably toolbar button usage) appear to be resolved in our testing.

PR: https://github.com/Automattic/wp-calypso/issues/5213
