### ISSUE TITLE
Node cannot be null or undefined

### ISSUE THREAD

**Issue by ghost** [tinymce/tinymce#4355]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Tons of uncaught errors are thrown.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**
http://fiddle.tinymce.com/zqgaab/4

**What is the expected behavior?**
No errors should be thrown.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
git bisect shows that the issue was introduced in commit e4026cd30a013a8f218f6f56220febbf9f89c167

**Comment by jhorowitz-firedrum** [comment]
In src/core/src/main/js/selection/SelectionRestore.js, moving
```javascript
if (editor.inline) {
  registerPageMouseUp(editor, throttledStore);
}
```
into the editor init callback fixes this issue.

**Comment by jhorowitz-firedrum** [comment]
@bago you might be interested in this too.

**Comment by jhorowitz-firedrum** [comment]
I've updated the fiddle to be as minimal as possible while still illustrating the issue, and added a few comments to the javascript to explain the process of triggering the bug.

**Comment by ethernidee** [comment]
Faced the same bug, thank you, ghost.

**Comment by cdmckay** [comment]
Anyone have a workaround other than editing the source code?

**Comment by cdmckay** [comment]
Here's the workaround I came up with. It's a bit hacky, but it seems to work:
```javascript
const tinymceBind = window.tinymce.DOM.bind;
window.tinymce.DOM.bind = (target, name, func, scope) => {
    // TODO This is only necessary until https://github.com/tinymce/tinymce/issues/4355 is fixed
    if (name === 'mouseup' && func.toString().includes('throttle')) {
        return undefined;
    } else {
        return tinymceBind(target, name, func, scope);
    }
};
```

**Comment by damms005** [comment]
Faced the same problem when doing `tinymce.init(...` before page load. Fixed it by doing `$( function() { tinymce.init(... } )`

**Comment by DNWEIJ** [comment]
i have this bug to. (5.2.0) Will this be fixed in the near future?

**Comment by Vidz51** [comment]
I am facing the same issue

**Comment by lnewson** [comment]
This issue should have been resolved back in TinyMCE 5.0.13. I attempted to use the original fiddle with TinyMCE 5.2.2 and it no longer throws an exception during init. For anyone still experiencing this issue, can you please provide a replication case?

**Comment by airasyaqub** [comment]
I am using my tinymce editor with angular form-group reactive forms using official wrapper. As per the standard functional flow in my component there is a global Redux state for progress bar with boolean value which gets set in HTTP interceptor accordingly. I subscribe to it and disable the form group when progress bar (means API call is in progress) is true and enable it when set to false. Disabling the form gives me 'Node cannot be null or undefined' error. which breaks everything and corrupts the form-group data too. A work around I had to do is disconnecting tinymce with form-group and manually updating form-control with tinymce content.

**Comment by c00** [comment]
I can confirm this error still occurs in version 5.6.2 of tinymce, with the official angular wrapper and angular 11.

In my case it happens when the component is loaded, then removed then loaded for a second time. The second time gives the error.

**Comment by rexebin** [comment]
TinyMCE is awesome, with the plugin system, it can do everything I ever wanted to do. Awesome stuff, thank you for your hard work and sharing with the community. 
I confirm I am getting this error in version "@tinymce/tinymce-react": "^3.12.2", tinymce 5.7.1. It happens when here: `editor.mode.set(canEdit ? 'design' : 'readonly')`. Everything seems to work perfectly, just the error message popping up every time I switch mode.

**Comment by 06180339** [comment]
I can also confirm with TinyMCE 5.7.1, initialization on mouseover, no framework except JQuery. One mouse-over init triggers lots of error messages `Uncaught Error: Node cannot be null or undefined` with the stacktrace (bottom-up): `loadScript, onload, u, u, Ce, u, ON, e, i, loadQueue, loadScripts, u, Ce, u, loadScript, onload, u, u, Ce, u, i, kN, hN, aN, aN, nN, tN, H, bind, _i, d, executeHandlers, n, setTimeout handler*throttle, o, o, rm, At`. (Doing `$( function() { tinymce.init(... } )` didnʼt work for me.)

By the way, TinyMCE is awesome, as the comment before stated.

**Comment by rexebin** [comment]
> TinyMCE is awesome, with the plugin system, it can do everything I ever wanted to do. Awesome stuff, thank you for your hard work and sharing with the community.
> I confirm I am getting this error in version "@tinymce/tinymce-react": "^3.12.2", tinymce 5.7.1. It happens when here: `editor.mode.set(canEdit ? 'design' : 'readonly')`. Everything seems to work perfectly, just the error message popping up every time I switch mode.

Apparently, there is another recommended way to switch between edit and read-only mode, that is through TinyMCE-react Editor's `disabled` prop. No more errors.

**Comment by marty30** [comment]
I've had the same error, but it only occurred after I closed the containing component. The problem was that I did not properly remove the old editor before initializing a new editor. This caused getBody to return null for the old editor. Simply calling tinymce.remove upon destroying the containing component solved my issue.

**Comment by amitava82** [comment]
I'm getting the same error with react. Though, there is no issue with the editor. Disabled suggestion didn't work. Is there any way to catch the error and prevent it from surfacing?

**Comment by vashisth00** [comment]
I am also getting same error I am using nextjs12 and tinymce editor

**Comment by oinochoe** [comment]
I have solved this issue as below code.
```
editor.on('init', function() {
   editor.on('keyup', function(e) {
       if(27 !== e.keyCode) {
         ~~~
        }
   });
});

```
