### ISSUE TITLE
feature request: clickable links in read-only editors

### ISSUE THREAD

**Issue by thorn0** [tinymce/tinymce#4396]
**Do you want to request a *feature* or report a *bug*?**

*feature*

**What is the current behavior?**

Links can't be clicked in a read-only editor.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**

http://fiddle.tinymce.com/4sgaab/1
It's not a bug, but it'd be logical to have an option to make links work. Blocking clicks on links doesn't really fit in with the general idea of inline editing. Hypertext should exhibit it's usual behavior when the edit mode is off.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**

It sort of worked before 4.7.12 because a private API could be used: `editor._clickBlocker.unbind();`
However, that API has been refactored away in https://github.com/tinymce/tinymce/commit/5d4e4d7c6f8ad722fd85c71405528e72a55ae5ab.

**Comment by hh54188** [comment]
I met this problem, too. Is there any plan to achieve this feature or fix this problem ?

**Comment by TheSpyder** [comment]
It used to be possible to select text in readonly mode, until the fix for #4249 (which @thorn0 linked in his report). We are tracking a new fix for this and will update this ticket when it's merged.

**Comment by wonderbugtiny** [comment]
This has been fixed in 5.0.6. Please let us know if you find any further problems. Thank you!

**Comment by shashankmeyar** [comment]
I am seeing this issue once again in tinymce@5.2.1, where a link is not clickable in readonly mode.

**Comment by lnewson** [comment]
@shashankmeyar I just tested and it's working fine for me in 5.2.1. Note that it should **not** work by just clicking the link, you'll need to "CTRL+click" or right click and open in a new tab. The reason being that clicking normally will navigate the user away from the content and potentially cause data to be lost, so we don't plan to allow that behaviour.

If you can still reproduce it taking into account the above, then please log a new issue.

**Comment by Dionnie123** [comment]
It's November 2024 and this issue still exists on Self Host TinyMCE, here's the fix without interfering the natural behavior of editor

```
   init={{
                            setup: function (editor) {
                              editor.on("init", function () {
                                // Add event listener for click events on links
                                editor
                                  .getDoc()
                                  .addEventListener("click", function (event) {
                                    const target = event.target;
                                    window.open(`${target}`, "_blank");
                                  });
                              });
                            },
```

and on the CSS file 

```
a {
  cursor: pointer !important;
  pointer-events: auto !important;
}

```

**Comment by aen1gma** [comment]
@Dionnie123 thank you! I really needed this
