### ISSUE TITLE
Unable to replace default icon in toolbar

### ISSUE THREAD

**Issue by plainnany** [tinymce/tinymce#4887]
I want to replace icon in toolbar (bold, code, save , etc) to my own icon, but I can't find any way, I read this issue [#1945](https://github.com/tinymce/tinymce/issues/1945), is there any configration so support this?

**Comment by lnewson** [comment]
@plainnany which version of TinyMCE are you using? As depending on what version you're using, will change your answer. For example, in TinyMCE 5, to override the default icons you'd just register a new icon with the same name and svg you want to use instead. eg:
```
editor.ui.registry.addIcon('bold', '<svg>...</svg>')
```

**Comment by plainnany** [comment]
> addIcon

my version is 5.0.1, I will try it, thanks

**Comment by plainnany** [comment]
@lnewson my verison is 5.0.1, I will try it, thanks a lot

**Comment by plainnany** [comment]
@lnewson I try to set  `editor.ui.registry.addIcon('bold', '<svg>test</svg>')`, just for test , but it doesn't work , is anything wrong?

**Comment by lnewson** [comment]
@plainnany for starters that's not a valid SVG, so you need to find an SVG to use there. I'd suggest something like IcoMoon or a similar service. However in saying that, I gave this a test myself using valid data and you're right it no longer works... I'm not sure if that's intended so I'll have to follow up internally on that. 

In that case, what you'd need to do is create an "Icon Pack", which currently isn't document, with your overrides and then use that via the icons setting. Here's an example: 

&lt;base url&gt;/icons/custom/icons.js:
```
tinymce.IconManager.add('custom', {
  icons: {
     'bold': '<svg>...</svg>'
  }
});
```

Init code:
```
tinymce.init({
  ...
  icons: 'custom'
});
```

Note:  `custom` is just a name and can be anything. However you need to be sure the name in the configuration and the url matches.

**Comment by plainnany** [comment]
@lnewson By the way , I'm using tinymce-react, and my code like this

```
 <Editor
      plugins='preview code link lists codesample image imagetools table save wordcount'
      toolbar='save code | bold italic underline strikethrough superscript subscript h1 h2 h3 removeformat | codesample blockquote bullist numlist link image file table | undo redo'
      // toolbar='customSave | customBold'
      init={{
          branding: false,
          menubar: false,
          min_height: 600,
          setup: editor => {
              // it doesn't work
              editor.ui.registry.addIcon('save', `<svg class="icon" aria-hidden="true">
                <use xlink:href="#icon-font-bold"></use>
              </svg>`);
             // it works
              editor.ui.registry.addButton('customBold', {
                text: `<svg class="icon" aria-hidden="true">
                  <use xlink:href="#icon-font-bold"></use>
                </svg>`,  
                tooltip: 'blod',
                onAction: function (_) {
                  editor.insertContent('<strong>test</strong>');
                },
              });
            },
          }}
      value={content}
      onEditorChange={this.handleEditorChange}
  />
```
I try to use `editor.ui.registry.addButton('customBold')` to custom my own button, and remove all default button in toolbar,  reset toolbar `toolbar='customBold'` it works, but in this way, all icon action, I need to rewrite , I just want to replace default icon to my own

**Comment by lnewson** [comment]
Yeah, I figured that was basically what you were trying to do. Unfortunately it seems a regression was introduced in 5.0.1, that prevents this from working sorry. So if you swap back to using 5.0.0 instead of 5.0.1 my original comment should work.

I've logged a task internally and am working on a fix, so it'll work again in 5.0.3.

**Comment by wonderbugtiny** [comment]
This should now be fixed in 5.0.3. Please let us know if you find any further problems!

**Comment by plainnany** [comment]
I find another way to change default icons, perhaps it not right, but it can work
```
editor.ui.registry.addToggleButton('customBold', {
      text: `<svg class="icon" aria-hidden="true">
          <use xlink:href="#icon-font-bold"></use>
      </svg>`, // your icon
      onAction: function (_) {
        editor.execCommand('mceToggleFormat', false, 'bold');
      },
      onSetup: function (api) {
        editor.formatter.formatChanged('bold', function (state) {
          api.setActive(state);
        });
      }
    });
```
[demo](https://codepen.io/plainnany/pen/VRGyxY)

**Comment by wonderbugtiny** [comment]
@plainnany I wouldn't recommend this workaround as this field is intended to be text only. So, we can't guarantee that it will continue to work in the future.

**Comment by plainnany** [comment]
@wonderbugtiny ok, got it.

**Comment by plainnany** [comment]
I notice that 5.0.3 has been released, and I try to set
```
editor.ui.registry.addIcon('bold', `
  <svg class="icon" aria-hidden="true">
       <use xlink:href="#icon-font-bold"></use>
  </svg>
`)
```
but it still can't work, anything wrong ?
[demo](https://codepen.io/plainnany/pen/eXPoqj)

**Comment by lnewson** [comment]
@plainnany you're using the 5 stable cloud version in that codepen, which is still running 5.0.2 as cloud runs off the enterprise releases. If you switch that to use `5-testing` or `5-dev` instead of `5` you'll see your changes.

**Comment by plainnany** [comment]
@lnewson yes , it works in 5.0.3, thanks

**Comment by plainnany** [comment]
@lnewson I find some icons can' be replaced, like `strikethrough bullist numlist removeformat blockquote`

**Comment by lnewson** [comment]
@plainnany the icon names don't always match the names of the buttons. If you want a list of icons being used, you can get that by running `editor.ui.registry.getAll().icons`. As an example, the icon for the `code` button is called `sourcecode`.

**Comment by TheSpyder** [comment]
The master list of default icons is here:
https://github.com/tinymce/oxide-icons-default/tree/master/src/svg

If you're replacing enough of the icons it would be far easier to build an icon pack and load it instead of replacing each individual icon at runtime. The full documentation isn't ready yet, but if you fork `oxide-icons-default`, build it and grab the `dist/icons/default/icons.js` file that it generates you can load that as an icon pack:
https://www.tiny.cloud/docs/configure/editor-appearance/#icons

To modify an icon simply replace the `.svg` file (filenames are used as icon names).

**Comment by plainnany** [comment]
@lnewson @TheSpyder thanks so much!

**Comment by gtraxx** [comment]
Hi, I try to integrate an icon svg to my plugin with your method but impossible to display it.
I used a fontawesome icon 5 : https://fontawesome.com/icons/youtube?style=brands

````javascript
editor.ui.registry.addIcon('youtube',
 '<svg width="24" height="24"><use xlink:href="'+url+'/img/youtube-brands.svg"></use></svg>'); 

editor.ui.registry.addButton('youtube',
 { icon: 'youtube', onAction: () => { _api = editor.windowManager.openUrl(_urlDialogConfig) } 
});
````

**Comment by nkunic** [comment]
It is important to use SVG with compound path.

I wanted to add custom svg icon that is not in some web icon set, and it worked for me like this in typescript:

`tinymce.init({

  toolbar: 'custombookmark',

  setup: function (editor: any) {

    function createCustomBookmark() {
      ...
    }

    editor.ui.registry.addIcon(
      'custombookmarkicon', 
      <svg width="28" height="25.1" id="Layer_1" data-name="Layer 1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 28 25.1"><path d="M14-.1,0,25H16.6L14,20.3H8.3L14,10.1l5.5,9.7L22.3,25H28Z" transform="translate(0 0.1)" fill="#98eef3"/></svg>'
    );

    editor.ui.registry.addButton('custombookmark', {
        icon: 'custombookmarkicon',
        tooltip: 'Custom bookmark',
        onAction: createCustomBookmark
    });  

  }

});  `

**Comment by electrotype** [comment]
Workaround by @plainnany (suing the `text` attribute) is the simplest. **Please** do NOT remove this functionality or, at least, make it off by default but configurable.

Here is how I use a Font Awesome icon in a TinyMCE 5 custom button:

```
tinymce.init({
    selector: '#something',
    toolbar: 'customButton',
    setup: function (editor) { 
        editor.ui.registry.addButton('customButton', {
            text: '<i class="fas fa-heart"></i>',
            onAction: function (_) {
              alert('Hello World!');
            }
          });
    }
}); 
```

**Comment by electrotype** [comment]
Hummm... For some reason, this doesn't seem to _always_ work. I see a broken character with some icons.

**Comment by electrotype** [comment]
It seens to be an issue with Font Waesome on my side because it works well with other font groups.

Another technic which work great is simply to use a `span` and style the button as you wish using CSS:

`text: '<span id="myCustomBtn"></span>',`

and, for example this CSS:

```
.tox #myCustomBtn:before {
    content:url('/public/images/icons/bgColor.png');
}
```
