### ISSUE TITLE
The character count is not translated

### ISSUE THREAD

**Issue by gergo85** [tinymce/tinymce#5071]
![charcount](https://user-images.githubusercontent.com/2959112/60872137-79625f80-a234-11e9-89d2-80ca1fcb335a.JPG)

**Comment by Kasheftin** [comment]
Excuse me, how was you able to put the character count there at all? I include the plugin wordscount and get the words count only, but can not set it into the characters mode.

**Comment by wonderbugtiny** [comment]
@gergo85 Thanks for the report! We are passing the word count string to be translated but the words seem to be missing from the list of strings that need a translation. We have created a ticket internally to update the translations. We will let you know when a fix is available.

@Kasheftin Clicking Word Count in the status bar switches between counting words and characters. A dialog box with both word and character counts can be opened using the menu item situated in the `Tools` drop-down, or the toolbar button. Please refer to the documentation for more information on the Word Count Plugin: https://www.tiny.cloud/docs/plugins/wordcount/

**Comment by wonderbugtiny** [comment]
@gergo85 Please note that there is also an option of adding the strings to the translation file by yourself, as demonstrated in the fiddle here: http://fiddle.tinymce.com/wMgaab

**Comment by Kasheftin** [comment]
@gergo85 thanks a lot! I still don't know the plugin system well. Could you please help with setting plugin's defaults? I need wordscount to be in character count mode by default.

**Comment by wonderbugtiny** [comment]
@Kasheftin We currently do not have an option to set the character count mode as default. If you would like this as a feature, please make a separate ticket and we will look into it. Thank you!

**Comment by lnewson** [comment]
Hi,

I've just checked the latest language packs available for download and they now include the missing word count plugin translations. I'm not sure when this was resolved, but I suspect it might have been when the TinyMCE 5.1 translations were pushed into transifex. Anyways, since this issue has been resolved I'm going to go ahead and close this. If you have any further issues, please let us know.

Thanks!
